### ISSUE TITLE
Server is failing to save

### ISSUE THREAD

**Issue by AM2i9** [lpregler/satisfactory-server-docker#1]
I'm trying to use this docker image, and it seems to be working well, except for the fact that I keep getting this error message
```
[2021.09.16-02.16.07:931][736]LogGame: World Serialization (save): 0.231 seconds
[2021.09.16-02.16.08:070][736]LogSave: Warning: Failed to save game, couldn't write file to disk
[2021.09.16-02.16.08:070][736]LogSave: Warning: FileStat is not valid, cannot verify integrity of save file! Will restore to Backup if Created
[2021.09.16-02.16.08:076][736]LogGame: Total Save Time took 0.376 seconds
```

And as I have unfortunately found, my game has not been saving, so we just lost almost 9 hours of playtime. Have you gotten the same problem?

**Comment by lpregler** [comment]
Hi, I'm sorry to hear about your lost progress (you might be able to recover it though :wink: ). Depending on your SSH setup the **save game file** you copied **might be write protected** by e.g. the `root` user:
```shell
steam@satis-test-server:~$ ls -l SaveGames/common/
-rw-r--r-- 1 root  root  1848347 Sep 16 20:45 SatisfactoryServer_autosave_0.sav
```
If this is the case for you, you need to adjust the save game file owner to your server user which is running the docker image. In my example the Satisfactory docker image is run by the user `steam` and I would need to do the following:
```shell
steam@satis-test-server:~$ cd SaveGames/common/
steam@satis-test-server:~/SaveGames/common$ sudo chown steam:steam SatisfactoryServer_autosave_0.sav
steam@satis-test-server:~/SaveGames/common$ ls -l
-rw-r--r-- 1 steam steam 1848347 Sep 16 20:45 SatisfactoryServer_autosave_0.sav
```

**Furthermore** you might be able to recover your lost progress as I mentioned previously. As far as I know the game creates three autosave files per default. Although it might not be able to overwrite the `SatisfactoryServer_autosave_0.sav` file, the other two autosave files (`SatisfactoryServer_autosave_1.sav` and `SatisfactoryServer_autosave_2.sav`) should have been created without any problem. So, in order to recover your progress (once you adjusted the file ownership), just manually overwrite the `SatisfactoryServer_autosave_0.sav` file with one of the other two save games, given they were not overwritten by a new game session yet:
```shell
steam@satis-test-server:~/SaveGames/common$ cp SatisfactoryServer_autosave_2.sav SatisfactoryServer_autosave_0.sav
```

**Comment by lpregler** [comment]
Moreover personally I was not able to connect to a server, based on the given docker image, anymore. For some reason the game automatically disconnects, every time I try to join the server. Also it is a real pain to rebuild the docker image each time there is an update to the experimental branch of Satisfactory.  
Therefore I decided for myself to wait for an official dedicated server instance to be provided by Coffee Stain Studios (apparently they are [making some progress](https://twitter.com/SatisfactoryAF/status/1433400814056493060)).

Nonetheless I am going to update the description to include the file ownership change. I hope this is going to fix your problem.

**Comment by lpregler** [comment]
@AM2i9 please let me know if the suggested action solves your problem, so I can close this issue.  
Of course I can continue searching for a solution, should your problem persist.

**Comment by AM2i9** [comment]
I tried messing around with permissions and ownership of the savegame, but it still is failing to save the file
```
steam@nighthawk:~/SaveGames/common$ ls -al
total 736
drwxr-xr-x 2 steam steam   4096 Sep 14 20:35 .
drwxr-xr-x 3 steam steam   4096 Sep 14 20:20 ..
-rwxrwxrwx 1 steam steam 742727 Sep 14 20:35 SatisfactoryServer_autosave_0.sav
```

I should also mention that it also did not create separate autosave files, so I do not believe that I can recover my lost progress 😔

**Comment by AM2i9** [comment]
If official dedicated servers are on the way though, I might just ditch trying to use a server in this manner until they come out. It might be a waste of time trying to solve an issue on something that will be obsolete in the near future.
